### ISSUE TITLE
After updating Microsoft.PowerShell.SDK Nuget from 7.2.7 to 7.3.0 I can't compile my app any more

### ISSUE THREAD

**Issue by KarloX2** [PowerShell/PowerShell#18752]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a .NET 6 app that used use the Nuget Microsoft.PowerShell.SDK version 7.2.7. After updating that Nuget to version 7.3.0 (the latest) I cannot compile my code any more.

Namespaces like these are not found any more:

```
    using System.Management.Automation;
    using System.Management.Automation.Runspaces;
```
The compiler gives me errors like this:
`Error	CS0234	The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)`

I can't find a list of breaking changes. Do I need any extra reference to make it work again?

Thanks!

### Expected behavior

```console
Compile with no errors after the Nuget update.
```

### Actual behavior

```console
Can't compile
```

### Error details

```console
Error CS0234
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SeeminglyScience** [comment]
7.3.0 requires a target of net7, have you changed that as well?

**Comment by KarloX2** [comment]
No I can't change the target at the moment.

I wanted to update to the latest to ensure that I don't miss any security relevant fixes that may have been done in PowerShell. Are there any such fixes between Version 7.2.7 and 7.3.0?

**Comment by SeeminglyScience** [comment]
Any security fixes that would be in 7.3.0 would be back ported to 7.2.x. I'd recommend checking out the [PowerShell Support Lifecycle](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle) docs for more info. Note that our support cycle matches .NET's, so 7.2.x will be supported as long as net6 is.

**Comment by KarloX2** [comment]
Okay, thank you!
