### ISSUE TITLE
Get-DscResource cannot find type [DSCResourceInfo]

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#2902]
Steps to reproduce
------------------

1. Launch `powershell_6.0.0.14.exe` that was installed by [PowerShell_6.0.0.14-alpha.14-win81-x64.msi](https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.14/PowerShell_6.0.0.14-alpha.14-win81-x64.msi).
2. Invoke `Get-DscResource File`

Expected behavior
-----------------

```PowerShell
PS C:\> Get-DscResource File
ImplementedAs   Name                      ModuleName                     Version    Properties                    
-------------   ----                      ----------                     -------    ----------                    
Binary          File                                                                {DestinationPath, Attribute...
```

Actual behavior
---------------

```PowerShell
PS C:\> Get-DscResource File
New-Object : Cannot find type
[Microsoft.PowerShell.DesiredStateConfiguration.DscResourceInfo]: verify that
the assembly containing this type is loaded.
At C:\program files\powershell\6.0.0.14\Modules\PSDesiredStateConfiguration\PSD
esiredStateConfiguration.psm1:4056 char:17
+ ... $resource = New-Object -TypeName Microsoft.PowerShell.DesiredStateCon ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentExcepti
   on
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewOb
   jectCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSEdition                      Core
CLRVersion
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.14
PSRemotingProtocolVersion      2.3
```

**Comment by SteveL-MSFT** [comment]
CC @Indhukrishna can you have someone investigate this?

**Comment by dermeister0** [comment]
Still does not work in PowerShell Core 6.0.2.

**Comment by SteveL-MSFT** [comment]
Also fails with 6.2.0-preview.1.  @nitinbps can you have someone take a look at this?

**Comment by nitinbps** [comment]
I will try to get it in before 6.2 GA.

**Comment by rdtechie** [comment]
Any plans to resolve this issue? Still occurring in 6.2.3:
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This has been fixed in PS7, we're not going to backport the fix to 6.2
