### ISSUE TITLE
CS0234 Namespace "Management" not found after update Microsoft.PowerShell.SDK from 7.2.7 to 7.3.0 

### ISSUE THREAD

**Issue by BornToBeRoot** [PowerShell/PowerShell#18513]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

See this Dependabot PR: https://github.com/BornToBeRoot/NETworkManager/pull/1689

& Build: https://ci.appveyor.com/project/BornToBeRoot/networkmanager/builds/45323761

i am using `using System.Management.Automation;` to create a PowerShell with `System.Management.Automation.PowerShell.Create()`.

```
error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?) [C:\projects\networkmanager\Source\NETworkManager.Models\NETworkManager.Models.csproj]
```

### Expected behavior

```console
Update from 7.2.7 to 7.3.0 should work.

Or at least have some docs about migrating this.
I cannot find anything about this in the changelog / docs / issues.
```

### Actual behavior

```console
error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
```

### Environment data

```powershell
Project is on .NET 6.x
```

**Comment by mehdifirefox** [comment]
Sorry I didn't open the new thread

I updated
But why was the new powershell installed?
Why didn't PowerShell update Windows?

Does this differ from the original?

**Comment by BornToBeRoot** [comment]
@mehdifirefox I do not know what this comment has to do with the error I have described above

**Comment by aluty** [comment]
I also encountered this error.
    <TargetFramework>net6.0</TargetFramework>
    
using System.Management.Automation;
using System.Management.Automation.Runspaces;
using System.ServiceProcess;
using Microsoft.PowerShell;

Only change was package upgrade.
-    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.2.7" />
+    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.3.0" />

error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
error CS0234: The type or namespace name 'PowerShell' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

**Comment by adityapatwardhan** [comment]
You would have to use .NET 7 for using 7.3.0 SDK

**Comment by BornToBeRoot** [comment]
@adityapatwardhan thanks for the feedback.

Is there still support for this library (like `7.2.8`, etc.) for .NET 6? I would like to stay on .NET 6 because it's LTS...

**Comment by adityapatwardhan** [comment]
Yes. The latest would be 7.2.7.

**Comment by aluty** [comment]
Would 6.x work for .net 6.0 or should still use 7.2.7?
If "breaking" change, why not major version update 8.x for .net 7.0 support?
Just trying to understand the versioning story.  Thanks.

**Comment by adityapatwardhan** [comment]
The versioning ideology is as below:

Major version - 7 (will change if there are significant changes to PowerShell language / engine etc)
Minor version - 3 (this changes with each version of .NET)
Patch - 1 (this changes with each servicing release)
Preview - Preview.1 (changes with each preview release)

Examples:

7.2.8 - PS 7 / .NET 6 / Servicing release 8
7.3.1 - PS 7 / .NET 7 / Servicing release 1
7.4.0-preview.1 - PS 7 / .NET 8 when it releases, previews included / preview 1

**Comment by adityapatwardhan** [comment]
@BornToBeRoot Is your issue resolved now? Can this issue be closed?

**Comment by BornToBeRoot** [comment]
@adityapatwardhan I think we can close the issue for now. I haven't upgraded my project to .NET 7.x so i can't test if 7.3.x works with the latest .NET.

But thanks for the example with the versioning. That makes it much clearer.

**Comment by abatishchev** [comment]
@adityapatwardhan 

> You would have to use .NET 7 for using 7.3.0 SDK

Is it documented anywhere? I don't see a clear mention of this in the [CHANGELOG/7.3](https://github.com/PowerShell/PowerShell/blob/master/CHANGELOG/7.3.md). Can you please add it?
