### ISSUE TITLE
ADSI : Error: "The value provided for adsObject does not implement IADs."

### ISSUE THREAD

**Issue by apetitjean** [PowerShell/PowerShell#8146]
I want to get local group membership, like for instance the "Administrators" group. It works with PowerShell 5.1, but not in PS Core 6.1.

Steps to reproduce
------------------

```powershell
$group = [ADSI]"WinNT://localhost/Administrators,group"
@($Group.psbase.Invoke("Members")) | foreach{([System.DirectoryServices.DirectoryEntry]$_)}
Cannot convert value "System.__ComObject" to type "System.DirectoryServices.DirectoryEntry". Error: "The value provided for adsObject does not implement IADs."
At line:1 char:46
+ ... ("Members")) | foreach{([System.DirectoryServices.DirectoryEntry]$_)}
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastConstructorException
```

Expected behavior
-----------------

For example:
```none
distinguishedName :
Path              : WinNT://MyComputerName/Administrator

distinguishedName :
Path              : WinNT://MyDomain/Workstation_Admins
```

Actual behavior
---------------

```none
Cannot convert value "System.__ComObject" to type "System.DirectoryServices.DirectoryEntry". Error: "The value provided for adsObject does not implement IADs."
At line:1 char:46
+ ... ("Members")) | foreach{([System.DirectoryServices.DirectoryEntry]$_)}
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastConstructorException
```

Environment data
----------------

Windows Server 2008R2, 2012R2, Windows 10

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
@daxian-dbw Could you please look the ComObject related issue?

**Comment by jzabroski** [comment]
I think this problem occurs because the default constructor for DirectoryEntry is `DirectoryEntry(object adsObject)` but there is an overload `DirectoryEntry(string path)` that probably makes more sense, but your type is not a string, its a COM Object.  That would likely mean not using `[ADSI]`.  The only object type you can pass into the default constructor is `System.DirectoryServices.Interop.UnsafeNativeMethods.IAds` (you need to decompile the code to verify this).

**Comment by SeeminglyScience** [comment]
This works for me now, probably due to the COM bits being added back to the runtime.

> The only object type you can pass into the default constructor is `System.DirectoryServices.Interop.UnsafeNativeMethods.IAds` (you need to decompile the code to verify this).

The COM objects returned by `Members` do implement that interface.  Does this still not work for you?

**Comment by jzabroski** [comment]
I was using a slightly different code snippet than @apetitjean . I ran @apetitjean snippet and confirm it returns correct results on my PowerShell 7 instance. 

@SteveL-MSFT  you can close this.

```powershell
PS D:\Users\John.Zabroski> $psversiontable
```
```
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I guess it was fixed by #13304.

**Comment by apetitjean** [comment]
Indeed it works perfectly now in PS 7.1!

It's even lightning fast (instantaneous) compared to Windows PowerShell.

You can close this issue. 
Thanks guys!

**Comment by apetitjean** [comment]
Indeed it works perfectly now in PS 7.1!

It's even lightning fast (instantaneous) compared to Windows PowerShell.

You can close this issue.
Thanks guys!
