### ISSUE TITLE
Escape char ` bug

### ISSUE THREAD

**Issue by inshua** [PowerShell/PowerShell#15760]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`new-object SYST`em`.Text.StringBuilder`
can work on powershell 5, but failed on 7.1.3

### Expected behavior

```console
PS C:\Users\Inshua> new-object SYST`em`.Text.StringBuilder

Capacity MaxCapacity Length
-------- ----------- ------
      16  2147483647      0
```

### Actual behavior

```console
PS C:\Users\Inshua> new-object SYST`em`.Text.StringBuilder
New-Object: Cannot find type [SYST.Text.StringBuilder]: verify that the assembly containing this type is loaded.
```

### Environment data

```powershell
PS C:\Users\Inshua> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

This command can work on system carried powershell
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by KalleOlaviNiemitalo** [comment]
That happens because `` `e `` now means the ESC character.

**Comment by inshua** [comment]
Yes, I find it in `tokenizer.cs`
```cs
private char Backtick(char c, out char surrogateCharacter)
      {
          surrogateCharacter = s_invalidChar;

          switch (c)
          {
              case '0':
                  return '\0';
              case 'a':
                  return '\a';
              case 'b':
                  return '\b';
              case 'e':
                  return '\u001b';    // **HERE**
              case 'f':
                  return '\f';
              case 'n':
                  return '\n';
              case 'r':
                  return '\r';
              case 't':
                  return '\t';
              case 'u':
                  return ScanUnicodeEscape(out surrogateCharacter);
              case 'v':
                  return '\v';
              default:
                  return c;
          }
      }
```

**Comment by KalleOlaviNiemitalo** [comment]
The changed meaning of `` `e `` was documented in [What's New in PowerShell Core 6.0](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/626a2949ecd07085dfbe5c7f51fa8a5c450ddd65/reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md#language-updates) but this documentation was lost in <https://github.com/MicrosoftDocs/PowerShell-Docs/pull/7756>. I think it would be good to document somewhere near [Implement Unicode escape parsing](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7#implement-unicode-escape-parsing), which describes `` `u ``.

**Comment by inshua** [comment]
Yes, thank you @KalleOlaviNiemitalo

**Comment by rkeithhill** [comment]
What exactly is the point of attempting to use `new-object SYST`em`.Text.StringBuilder` instead of `new-object System.Text.StringBuilder`?

**Comment by inshua** [comment]
> What exactly is the point of attempting to use:
> 
> ```powershell
> new-object SYST`em`.Text.StringBuilder
> ```
> 
> instead of `new-object System.Text.StringBuilder`?

It come from some malicious code.

**Comment by vexx32** [comment]
Yeah, it's generally just used by malware trying to evade AV detection in scripts. Dunno why stringbuilder specifically would be useful, but it's a common tactic.

If you ask me, the fact that a case like this broke is probably a bonus 😂
