### ISSUE TITLE
Build on macOS 10.12 fails due to deprecated system call

### ISSUE THREAD

**Issue by nocentino** [PowerShell/PowerShell#2633]
Steps to reproduce
------------------
Execute build as documented in https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md and https://github.com/PowerShell/PowerShell/blob/master/docs/building/macos.md

Expected behavior
-----------------
Successful build of PowerShell on macOS

Actual behavior
---------------
The build fails with an error saying there's a call to a deprecated system call on macOS 10.12.

..PowerShell-repo/src/libpsl-native/src/getcurrentthreadid.cpp:14:11: error: 'syscall' is deprecated: first
      deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost().
      [-Werror,-Wdeprecated-declarations]
    tid = syscall(SYS_thread_selfid);
          ^
/usr/include/unistd.h:733:6: note: 'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
         ^
1 error generated.
make[2]: *** [src/CMakeFiles/psl-native.dir/getcurrentthreadid.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object test/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
make[1]: *** [src/CMakeFiles/psl-native.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 52%] Linking CXX static library "../PowerShell-repo/src/powershell-unix/libgtest.a"
[ 52%] Built target gtest
make: *** [all] Error 2
Execution of { make -j } failed with exit code 2
At ../PowerShell-repo/build.psm1:2091 char:13
             throw "Execution of {$sb} failed with exit code $LASTEXIT ...
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Execution of { ...ith exit code 2:String) [], RuntimeException
    + FullyQualifiedErrorId : Execution of { make -j } failed with exit code 2

Environment data
----------------

<!-- provide the output of $PSVersionTable -->

```powershell
> $PSVersionTable

```

**Comment by Carringguns** [comment]
# I'm using an Android# 

__ is this _compatable?_



> Successful build of PowerShell on 

> macOS

**Comment by andschwa** [comment]
Resolved by #2675.
