### ISSUE TITLE
Cannot run Powershell 6 Beta on OS X 10.11

### ISSUE THREAD

**Issue by samirageb** [PowerShell/PowerShell#3834]
This is likely a known issue, but not listed anywhere as an issue (except by being absent from the target system requirements). For those that haven't updated to MacOS Sierra, PoSH 6 won't run at all. I'm just one rev behind (El Capitan) and cannot launch the new PoSh at all.

Steps to reproduce
------------------
Install MacOS 6.x Beta however you choose, even via homebrew `brew cask install powershell`
After installation, just run `powershell` at terminal window

Expected behavior
-----------------
PoSH cmd prompt

Actual behavior
---------------
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/microsoft/powershell/6.0.0-beta.1/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/microsoft/powershell/6.0.0-beta.1/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

[1]    94185 trace trap  powershell

Environment data
----------------

N/A since you can't run powershell cmd

**Comment by SteveL-MSFT** [comment]
We've moved to dotnetcore 2.0 which is not supported on 10.11

https://github.com/PowerShell/PowerShell/issues/3749

**Comment by meet-bhagdev** [comment]
How do get powershell to work on 10.1!?

**Comment by hookbot** [comment]
I'm having the same problem, but your instructions are not clear. What is the solution to actually get PoSH working on Mac OSX?

**Comment by iSazonov** [comment]
You should ask CoreFX team to support MacOs 10.11.

**Comment by hookbot** [comment]
Wait! I'm currently running Yosemite (10.10.x). So you're saying the solution is to just switch to Sierra (10.12.x) or later?

$ powershell
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/microsoft/powershell/6.0.0-beta.8/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
$

**Comment by iSazonov** [comment]
PowerShell Core is based on .Net Core 2.0.
.Net Core 2.0 support MacOs 10.12+ https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md

**Comment by samirageb** [comment]
I came to the same conclusion as @iSazonov and upgraded to Sierra, installed .NET Core 2.0, then PoSH and everything works fine.
