### ISSUE TITLE
Separate out Parser as independent nupkg

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#7408]
Problem statement:
- I would like to use a self-contained version of the Parser in an application that uses the full .Net Framework (4.7.2), however, due to the `System.Management.Automation` NuGet package being compiled and published against `netcoreapp2.1`, I cannot use it in full .Net, even when trying to use it in a .Net Standard project and publishing a self-contained version of it. I would like to have a compiled version of it to be able to run it in full .Net, even limited functionality (i.e. only having the Parser working but not being able to host a runtime) would be OK for my scenario.

Would it be feasible (with reasonable effort) and would a PR be accepted to allow compilation and publication against `netstandard2.0`? Or is there a better way of using and shipping a self-contained version of the Parser in full .net, i.e. to not having to depend on the installed version of PowerShell? @SteveL-MSFT 

As far as I can see the dependent project ` Microsoft.PowerShell.CoreCLR.Eventing` would need to be changed to target `netstandard2.0` as well. A quick experiment shows that most compilation errors can be resolved by adding the `System.Reflection.Emit`, `System.Reflection.Emit.Lightweight`, `System.Memory`, `System.Collections.Immutable` and `System.Runtime.Loader` NuGet packages to SMA, the remaining compilation errors that would need to be resolved are only about the `EnumerationOptions` type not  being available in .Net Standard and seemed to be not too difficult to handle via conditional compilation to use an overload of `Directory.GetDirectories` without `EnumerationOptions` the  (and by looking at the history, those new API calls were only recently added by @daxian-dbw  as an optimisation)
```
D:\PowerShell\src\System.Management.Automation\engine\Modules\ModuleUtils.cs(17,43): error CS0234: The type or namespace name 'EnumerationOptions' does not exist in the namespace 'System.IO' (are you missing an assembly reference?) [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\Modules\ModuleUtils.cs(24,43): error CS0234: The type or namespace name 'EnumerationOptions' does not exist in the namespace 'System.IO' (are you missing an assembly reference?) [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
```

After resolving them, I suddenly got a lot more compilation errors, some I can resolve, but some about dynamics are a bit tricky and don't have a blame history other than the initial commit (not even in the source depot branch) to figure out how code was converted from full .net to netcore as a hint on how to make it netstandard compliant.
```
D:\PowerShell\src\System.Management.Automation\engine\ExperimentalFeature\GetExperimentalFeatureCommand.cs(103,50): error CS1061: 'Dictionar
Add' and no extension method 'TryAdd' accepting a first argument of type 'Dictionary<string, ExperimentalFeature>' could be found (are you m
\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\Modules\ModuleSpecification.cs(314,20): error CS0103: The name 'HashCode' does not exi
ion\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\Modules\ModuleCmdletBase.cs(2407,37): error CS1503: Argument 1: cannot convert from 'c
m.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\Modules\ImportModuleCommand.cs(643,53): error CS1503: Argument 1: cannot convert from
tem.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\namespaces\EnvironmentProvider.cs(201,36): error CS1061: 'Dictionary<string, DictionaryEntry>
TryAdd' accepting a first argument of type 'Dictionary<string, DictionaryEntry>' could be found (are you missing a using directive or an ass
em.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(431,42): error CS0656: Missing compiler requ
 [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\parser\PSType.cs(1237,56): error CS1061: 'TypeBuilder' does not contain a definition f
 argument of type 'TypeBuilder' could be found (are you missing a using directive or an assembly reference?) [D:\PowerShell\src\System.Manag
D:\PowerShell\src\System.Management.Automation\engine\parser\PSType.cs(1240,75): error CS1061: 'TypeBuilder' does not contain a definition f
 argument of type 'TypeBuilder' could be found (are you missing a using directive or an assembly reference?) [D:\PowerShell\src\System.Manag
D:\PowerShell\src\System.Management.Automation\engine\DscResourceSearcher.cs(136,25): error CS0656: Missing compiler required member 'Micros
\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(2871,46): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(2927,42): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(3018,42): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(3150,37): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(3227,38): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(3275,42): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(3326,46): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(3405,38): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(3463,46): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(3526,38): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(4107,40): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs(4623,32): error CS0656: Missing compiler req
' [D:\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\PSVersionInfo.cs(647,34): error CS1503: Argument 1: cannot convert from 'char' to 'str
.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\PSVersionInfo.cs(647,59): error CS1503: Argument 1: cannot convert from 'char' to 'str
.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\PSVersionInfo.cs(647,84): error CS1503: Argument 1: cannot convert from 'char' to 'str
.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs(2707,29): error CS0656: Missing compiler required member
hell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PowerShell\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs(3017,32): error CS0656: Missing compiler required member
hell\src\System.Management.Automation\System.Management.Automation.csproj]
```

Is it easier to try to make it compile it directly `net472`?

**Comment by SteveL-MSFT** [comment]
The use case is valid, but currently it's probably not trivial to get SMA.dll and dependent assemblies to build targeting .Net Std 2.0.  We should eventually see what that would take and add that as a supported runtime in the SMA nupkg.  For now, unless you want to complete this work and submit as a PR, it would be easier to multi-target net472 and netcoreapp21 (assuming you want it to work in PSCore6.1).

**Comment by iSazonov** [comment]
`System.Reflection.Emit` and `System.IO.Enumeration` will in .Net Standard 2.1 
https://github.com/dotnet/standard/tree/master/docs/planning/netstandard-vnext#major-features

We could wait .Net Standard 2.1 - with it the solution will be easier.

**Comment by bergmeister** [comment]
I tried compiling against net461 today, some code inside `#if !CORECLR` seems to not work any more due missing implementations, one of them being Snapins, so I just commented some of that code out for a proof of concept (the work is [here](https://github.com/bergmeister/PowerShell/commit/4ec12c11e5c955d55cf35a653383acde83d0a60d)).
After a while I am left with only 1 compilation error, which is due to the missing implementation of `PowerShellAssemblyLoadContext` in the `ClrFacade` [here](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/utils/ClrFacade.cs#L37) and I could not find an implementation of it in the code base for full .net (I also looked in the source depot branch for it).
I am also having some errors with the type generation that I still need to look into. Any help/pointers would be appreciated.

**Comment by SteveL-MSFT** [comment]
The `PowerShellAssemblyLoadContext` code was originally wrapped by `#if CORECLR` pragmas as it wasn't needed by .NET Framework.

**Comment by iSazonov** [comment]
I believe that the main direction of development is migration from .Net Framework to .Net Core. So I would not invest in compatibility with .Net Framework. Seem some of .Net Standard 2.0 is already lacking in .Net Framework. With .Net Standard 2.1, the outbreak will increase. 
I expect that PowerShell Core will be consistent (compiled) with .Net Standard Future in a few years and again the outbreak with .Net Framework will increase.
Also if we'll add improvements in Parser with Span\<T>, Memory\<T> and Buffers we can not compile the Parser in .Net Framework at all.

**Comment by iSazonov** [comment]
@bergmeister MSFT announced .Net Core 3.0 Preview will be released later _this_ year. Seems .Net Standard too. I do believe that it is more profitable for you to start working in this direction now.

**Comment by bergmeister** [comment]
I have a working prototype in my branch [here](https://github.com/bergmeister/PowerShell/tree/SMAOnFullDotnet) that needed special treatment only in a few places and some WIndows PowerShell Code to be brought back. As an alternative, one could've also just removed some `#if !CORECLR` sections that required those treatments, some of them like PSSnapins would even make sense to be completely removed. Therefore I do not see much of a burden to re-enable compilation against fullclr with only a compilation check in CI. I saw only 5 method calls that used new .Net Core 2.1 APIs that are not available in `net472`, the rest (like e.g. Spans) could all be brought back to full .Net via NuGet packages. Not setting the `CORECLR` constant for compilation against full .net requires to either remove some fullclr code (some of it would makes sense, like e.g. Snapins) or to bring back some fullclr code that is just not compiled at the moment or in the source-depot branch.
I do not expect full support from MSFT for an SMA package compiled against fullclr, but having it in the mainstream branch and it being published by MSFT would be helpful.
Since compilation against netstandard is not trivial and and `netstandard2.1` is not even out yet, I'd agree with @SteveL-MSFT that multi-targeting for `net472` (and fullclr?) is the easiest option where I can issue a PR *now*
Separating out the Parser seemed to me to be quite difficult.
Can MSFT please state if it is OK to multi-target SMA for `net472` and if the `CORECLR` compile constant should be set in this case.

**Comment by SteveL-MSFT** [comment]
@bergmeister I don't think we want to bring FullCLR code back into the code base as it makes changes complicated and we don't validate the FullCLR code.  It would be better if you need this to fork the project and maintain what you need until netstandard2.1 is available and (ideally) resolves the need to multi-target

**Comment by bergmeister** [comment]
@SteveL-MSFT  OK, I will then not bring FullCLR code back and I am OK with this decision as I can understand the reasoning. But are you also saying that
a) Code that was written for the CORECLR would actually work with the fullclr that `net472` uses under the hood? My initial thoughts were that some of the code is coreclr specific.
b) That a PR that multitargets `netcoreapp2.1` and `net472` would be acceptable if the compilation for `net472` also defines the `CORECLR` constant, i.e. uses the `coreclr` code? Or would you still prefer to wait for `netstandard2.1` in this case as well?

**Comment by SteveL-MSFT** [comment]
Until we have `netstandard2.1` I can't say what work is needed to make it work under `net472`.  There is another effort to refactor SMA.dll making it smaller for hosting PowerShell.  This may be what you actually need although my initial thinking was for .NET Core, but perhaps we should consider .NET Framework as well (cc @BrucePay).

In general, we've been trying to clean up the `#if CORECLR` or `#if !CORECLR` out of the code base to make it more maintainable, so adding back changes to enable multi-targeting `netcoreapp` and `net472` would be counter-productive.

**Comment by bergmeister** [comment]
@SteveL-MSFT Details about `netstandard2.1` were recently announced [here](https://blogs.msdn.microsoft.com/dotnet/2018/11/05/announcing-net-standard-2-1/) and the gist is that only .Net Core 3.0 will implement it but not the current 2.1 and 2.2 versions and neither will the full .Net Framework (even 4.8 was ruled out).
Since the current state of SMA is far away from being able to work using `netstandard2.0` (due to special compiler binding calls and Spans), the only alternative is to multi-target `net472`. I already did a prototype a few months ago and there are actually not too many adaptions that are needed since most of the new features can brought to `net472` via NuGet packages (e.g. Spans), in total there are only around 10 cases where a slightly different API call is needed or an extension method needs to be created to adapt for `net472`. Would you accept such a PR?

**Comment by SteveL-MSFT** [comment]
@bergmeister unless there are other use cases to multi-target, it seems that separating the parser as it's own nupkg may be a better long term solution

**Comment by iSazonov** [comment]
I discover that the parser intersect with HelpSystem. We need to investigate how split them in better way. Can we get `ExecutionContext` (there `HelpSystem` is initialized) in the parser (ast)?

**Comment by SteveL-MSFT** [comment]
@bergmeister for sure separating out the parser is a non-trivial task.  Targeting `net472` is problematic as we've be removing `#if !CORECLR` to have a cleaner code base targeting .NET Core and started using new types that aren't available in .NET Framework.

**Comment by iSazonov** [comment]
Over time, the gap between net standard and .net framework will only increase (last annouce is that .net framework will do not support netstatndard 2.1 but PowerShell Core could seems be compiled against one.). I think it will force PSAnalyzer to change its archetecture.

**Comment by lzybkr** [comment]
@bergmeister - I wouldn't move all files - e.g. compiler.cs isn't useful outside of the engine.

**Comment by rjmholt** [comment]
If we went down the path of putting the parser into its own project, I think it would be important to work out what the conceptual cohesion of that project would be.

I imagine that project's conceptual purpose would be to ingest PowerShell script input and output a PowerShell AST, which is then input to the engine. But that's just my quick imagining. @lzybkr, @BrucePay and @daxian-dbw might have a better conception of what belongs in that project.

**Comment by iSazonov** [comment]
I see DSC in the Parser and it creates Runspace and PowerShell objects. This makes it impossible to decouple the parser in a separate package. 
Is DSC needed for PSSA and PSES?

**Comment by bergmeister** [comment]
@iSazonov PSSA has DSC specific rules and using the `-SaveDSCDependency` switch, it downloads required modules from the PSGallery by parsing occurrences of `Import-DSCResource` so that it can later load them into a runspace in order to be able to parse a DSC script, therefore I _think_ that PSSA does not need public Parser APIs for DSC but it probably needs the parser to 'work' when parsing a DSC resource.
https://github.com/PowerShell/PSScriptAnalyzer/blob/b1a81874fbe61ebaf1a0b9631f337b4f06296625/Engine/Generic/ModuleDependencyHandler.cs#L424

**Comment by iSazonov** [comment]
>  it can later load them into a runspace in order to be able to parse a DSC script

@bergmeister Who creates the runspace?

**Comment by bergmeister** [comment]
@iSazonov PSSA creates the runspace [here](https://github.com/PowerShell/PSScriptAnalyzer/blob/b407e8ee2b5b4d0e227cc7425311c6333db352fc/Engine/Commands/InvokeScriptAnalyzerCommand.cs#L370). What happens is that if calling `Parser.ParseFile` fails [here](https://github.com/PowerShell/PSScriptAnalyzer/blob/b1a81874fbe61ebaf1a0b9631f337b4f06296625/Engine/ScriptAnalyzer.cs#L1858), then it extracts the missing module names based on parsing extents of `Import-DSCResource` or the error message and then downloads them to a local temp folder [here](https://github.com/PowerShell/PSScriptAnalyzer/blob/b1a81874fbe61ebaf1a0b9631f337b4f06296625/Engine/ScriptAnalyzer.cs#L1867), which it temporarily adds to the `PSModulePath` environment variable [here](https://github.com/PowerShell/PSScriptAnalyzer/blob/b407e8ee2b5b4d0e227cc7425311c6333db352fc/Engine/Generic/ModuleDependencyHandler.cs#L215) so that the Parser can pick up the downloaded dependencies

**Comment by iSazonov** [comment]
Looking the PSSA code I see that it utilizes _full PowerShell Engine_ and I wonder that you request standalone nupkg for Parser.

**Comment by bergmeister** [comment]
@iSazonov At the time being the request was for a company internal tool that only needed the Parser for static script parsing, which was not as involved as PSSA. I'm not working on that project any more but the request for having a nupkg for the Parser in general is still valid I think and has multiple use cases.

**Comment by iSazonov** [comment]
@rjmholt Could you please share how PSES uses the Parser? Can it really benefit from the standalone Parser or we have the same as for PSSA?

**Comment by rjmholt** [comment]
PSES uses the parser to perform script file analysis, like reference discovery, but it also runs PowerShell. PSES integrates with the installed PowerShell on a system and won't run without it, so there's no strong need for a standalone parser, but it would add universality perhaps. I think PSSA has a much stronger need, since it's used to analyse scripts going to other PowerShell implementations.
