### ISSUE TITLE
Add-Type Mismatched Assemblies

### ISSUE THREAD

**Issue by IanBAdams** [PowerShell/PowerShell#14096]
## Steps to reproduce

```powershell
Copy and paste the following code into a PowerShell 7.1 console.

If ($PSEdition -Eq 'Core' -And $PSVersionTable.PSVersion.ToString() -Like '7.*') {
    $ReferencedAssemblies = 'System.Management.Automation.dll','System.Drawing.dll','PresentationFramework.dll','PresentationCore.dll','WindowsBase.dll','System.Xaml.dll'
} ElseIf ($PSEdition -Eq 'Desktop' -And $PSVersionTable.PSVersion.ToString() -Like '5.1.*') {
    $ReferencedAssemblies = 'System.Management.Automation.dll','System.Drawing.dll','WPF\PresentationFramework.dll','WPF\PresentationCore.dll','WPF\WindowsBase.dll','System.Xaml.dll'
} Else {
    Throw 'Unsupported PowerShell version.'
}
Add-Type -ReferencedAssemblies $ReferencedAssemblies -TypeDefinition @"
using System.Management.Automation;
using System.Windows.Media;
using System.Drawing;

namespace AnyBox
{
    public enum InputType {
        None, Text, FileOpen, FileSave, FolderOpen, Checkbox, Password, Date, Link
    };
    public enum MessagePosition { Top, Left };
    public enum SetPresentation { ComboBox, Radio, Radio_Wide };
    public enum DataGridSelectionMode { None, SingleCell, SingleRow, MultiRow };

    public enum WindowStartupLocation { Center, Top, TopLeft, TopRight, Bottom, BottomLeft, BottomRight };

    public class AnyBox
    {
        public string Icon;
        public string Title;
        public string Image;
        public string[] Message;
        public object[] Prompts;
        public object[] Buttons;
        public string CancelButton;
        public string DefaultButton;
        public System.UInt16 ButtonRows = 1;
        public string[] Comment;
        public string ContentAlignment = "Left";
        public bool CollapsibleGroups;
        public bool CollapsedGroups;
        public System.Management.Automation.ScriptBlock PrepScript;
        public System.Windows.Media.FontFamily FontFamily = new System.Windows.Media.FontFamily("Segoe UI");
        public System.UInt16 FontSize = 12;
        public System.Windows.Media.Brush FontColor = System.Windows.Media.Brushes.Black;
        public System.Windows.Media.Brush BackgroundColor;
        public System.Windows.Media.Brush AccentColor = System.Windows.Media.Brushes.Gainsboro;
        public System.Windows.WindowStyle WindowStyle = System.Windows.WindowStyle.SingleBorderWindow;
        public System.Windows.ResizeMode ResizeMode = System.Windows.ResizeMode.CanMinimize;
        public bool NoResize;
        public System.UInt16 MinHeight = 50;
        public System.UInt16 MinWidth = 50;
        public System.UInt16 MaxHeight = 0;
        public System.UInt16 MaxWidth = 0;
        public bool Topmost;
        public bool HideTaskbarIcon;
        public System.UInt32 Timeout;
        public bool Countdown;
        public bool ProgressBar;
        public System.Management.Automation.ScriptBlock While;
        public WindowStartupLocation WindowStartupLocation = WindowStartupLocation.Center;
        public System.Windows.Window ParentWindow;
        public object[] GridData;
        public bool GridAsList;
        public DataGridSelectionMode SelectionMode = DataGridSelectionMode.SingleCell;
        public bool NoGridSearch;
    }

    public class Prompt
    {
        public string Name;
        public string Tab;
        public string Group;
        public InputType InputType = InputType.Text;
        public string Message;
        public MessagePosition MessagePosition = MessagePosition.Top;
        public string Alignment;
        public System.UInt16 FontSize;
        public string FontFamily;
        public string FontColor;
        public string DefaultValue;
        public System.UInt16 LineHeight = 1;
        public bool ReadOnly = false;
        public string[] ValidateSet;
        public SetPresentation ShowSetAs = SetPresentation.ComboBox;
        public string RadioGroup;
        public bool ValidateNotEmpty = false;
        public System.Management.Automation.ScriptBlock ValidateScript;
        public bool ShowSeparator = false;
        public bool Collapsible = false;
        public bool Collapsed = false;
    }

    public class Button
    {
        public string Name;
        public string Text;
        public string ToolTip;
        public bool IsCancel = false;
        public bool IsDefault = false;
        public System.Management.Automation.ScriptBlock OnClick;
    }
}
"@ -ErrorAction 'Stop'


```

## Expected behavior

```none
The above code should complete without errors. This is the case with PowerShell 5.1.* and 7.0.*.

The above code is part of dm3ll3n / AnyBox from GitHub which my scripts use. Originally the code did not work with PowerShell 7.0.* but a simple amendment of the -ReferencedAssemblies corrected this.

```

## Actual behavior

```none
Receive the following error:

Add-Type: error CS1705: Assembly 'PresentationCore' with identity 'PresentationCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'WindowsBase, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'WindowsBase' with identity 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

The only open issues I can find that look remotely similar were: #3779, #9599 and #12781. However, they seemed to be more about missing assemblies rather than mismatched versions.


```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by IanBAdams** [comment]
By replacing the code:

If ($PSEdition -Eq 'Core' -And $PSVersionTable.PSVersion.ToString() -Like '7.*') {
    $ReferencedAssemblies = 'System.Management.Automation.dll','System.Drawing.dll','PresentationFramework.dll','PresentationCore.dll','WindowsBase.dll','System.Xaml.dll'
} ElseIf ($PSEdition -Eq 'Desktop' -And $PSVersionTable.PSVersion.ToString() -Like '5.1.*') {
    $ReferencedAssemblies = 'System.Management.Automation.dll','System.Drawing.dll','WPF\PresentationFramework.dll','WPF\PresentationCore.dll','WPF\WindowsBase.dll','System.Xaml.dll'
} Else {
    Throw 'Unsupported PowerShell version.'
}

within the Steps to reproduce section by:

If ($PSVersionTable.PSVersion.ToString() -Like '7.0.*') {
    $ReferencedAssemblies = 'System.Management.Automation.dll','System.Drawing.dll','PresentationFramework.dll','PresentationCore.dll','WindowsBase.dll','System.Xaml.dll'
} ElseIf ($PSVersionTable.PSVersion.ToString() -Like '7.1.*') {
    $PwshPath = Split-Path -Parent (Get-Command -Name pwsh.exe).Path
    $ReferencedAssemblies = "$PwshPath\System.Management.Automation.dll","$PwshPath\System.Drawing.dll","$PwshPath\PresentationFramework.dll","$PwshPath\PresentationCore.dll","$PwshPath\WindowsBase.dll","$PwshPath\System.Xaml.dll"
} ElseIf ($PSVersionTable.PSVersion.ToString() -Like '5.1.*') {
    $ReferencedAssemblies = 'System.Management.Automation.dll','System.Drawing.dll','WPF\PresentationFramework.dll','WPF\PresentationCore.dll','WPF\WindowsBase.dll','System.Xaml.dll'
} Else {
    Throw 'Unsupported PowerShell version.'
}
Add-Type -ReferencedAssemblies $ReferencedAssemblies -TypeDefinition @"

seems to allow the code to complete successfully and allows dm3ll3n / AnyBox from GitHub to work as expected against PowerShell versions 5.1, 7.03 and 7.1. I haven’t installed PowerShell 7.2 but I would guess similar code to that used for 7.1 may be required.

Whether or not I should have to fully qualify the paths for the referenced assemblies for PowerShell version 7.1 isn’t clear to me. The documentation for Add-Type indicates that Add-Type looks for assemblies in a ref folder under the folder that contains pwsh.dll. However, this does not contain System.Management.Automation.dll but this is included within the folder that contains pwsh.dll. The documentation also indicates that the default .NET assemblies are no longer included by default from PowerShell 6 but I don’t have to fully qualify the assemblies for version 7.0. So, I’m a bit confused (nothing new there). Anyway, I thought I would post my findings so that changes could be made, if necessary. In the meantime, I’m happy because I’ve got something I can continue testing my scripts against PowerShell 7.1 with.

**Comment by iSazonov** [comment]
It seems we have a separate issue to improve how Add-Type cmdlet works/finds reference assemblies.

**Comment by redoz** [comment]
@iSazonov Do you have a reference to that issue? I just discovered one of my old PS modules also broke due to this.

**Comment by iSazonov** [comment]
> I just discovered one of my old PS modules also broke due to this.

I guess you need to manually create right reference as demonstrated above.

**Comment by doctordns** [comment]
The WG has reviewed this issue. We feel that PowerShell (core) is working as intended. To answer the later question, yes,you need to supply fully qualified assembly names as there is no GAC with .NET Core. We also think the documentation could be improved to clarify this point
